const products=[
 {title:'Tende da sole',group:'Tende',text:'A bracci, a caduta, a cappottina ed ermetiche. Trova il modo giusto di vivere l’ombra.',tile:[0,0]},
 {title:'Tende da interno',group:'Tende',text:'Tessuti e trasparenze per rendere la luce più morbida e dare carattere alla casa.',tile:[50,0]},
 {title:'Pergole e outdoor',group:'Outdoor',text:'In piano con telo, con alette e bioclimatiche: nuove possibilità per i tuoi spazi esterni.',photo:'terrazza.png'},
 {title:'Infissi in PVC e alluminio',group:'Infissi e schermature',text:'Materiali e finiture per valorizzare ogni apertura e completare i tuoi ambienti.',tile:[100,0]},
 {title:'Portoni, cancelli e grate',group:'Sicurezza',text:'Portoni blindati, cancelli e grate per la protezione degli accessi di casa.',tile:[0,100]},
 {title:'Persiane e avvolgibili',group:'Infissi e schermature',text:'Persiane in alluminio, persiane blindate in ferro e avvolgibili per luce e riservatezza.',tile:[50,100]},
 {title:'Zanzariere',group:'Infissi e schermature',text:'Per aprire la casa all’aria e tenere fuori gli insetti.',tile:[100,100]},
 {title:'Vetrate panoramiche',group:'Outdoor',text:'Trasparenze che creano continuità con l’esterno e lasciano spazio alla vista.',photo:'vetrate-montagne.png'},
 {title:'Pavimenti in legno e pedane',group:'Outdoor',text:'Il calore del legno per terrazze, percorsi e angoli da vivere.',photo:'tenda-naturale.png'}
];
const list=document.querySelector('.products'),select=document.querySelector('#interest');
products.forEach((product,i)=>{const card=document.createElement('article');card.className='product';card.dataset.group=product.group;const visual=document.createElement('div');visual.className='product-visual';if(product.tile){visual.classList.add('atlas');visual.style.backgroundPosition=product.tile.map(n=>n+'%').join(' ');visual.setAttribute('role','img');visual.setAttribute('aria-label',product.title+' — immagine d’ispirazione')}else{const img=document.createElement('img');img.src=product.photo;img.alt=product.title+' — immagine d’ispirazione';img.loading='lazy';img.width=1536;img.height=1024;visual.append(img)}const tag=document.createElement('span');tag.className='product-label';tag.textContent=String(i+1).padStart(2,'0')+' / '+product.group.toUpperCase();const title=document.createElement('h3');title.textContent=product.title;const p=document.createElement('p');p.textContent=product.text;const link=document.createElement('a');link.href='#contatti';link.textContent='Parliamo del tuo progetto';link.onclick=()=>select.value=product.title;card.append(visual,tag,title,p,link);list.append(card);select.add(new Option(product.title,product.title))});select.add(new Option('Vorrei un consiglio','Vorrei un consiglio'));
const count=document.querySelector('#count');count.textContent='9 soluzioni · Immagini illustrative create con AI.';
['Tutte','Tende','Outdoor','Infissi e schermature','Sicurezza'].forEach((group,i)=>{const button=document.createElement('button');button.type='button';button.textContent=group;button.setAttribute('aria-pressed',String(i===0));button.onclick=()=>{document.querySelectorAll('.filters button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let visible=0;list.querySelectorAll('.product').forEach(c=>{c.hidden=group!=='Tutte'&&c.dataset.group!==group;if(!c.hidden)visible++});count.textContent=visible+(visible===1?' soluzione':' soluzioni')+' · Immagini illustrative create con AI.'};document.querySelector('.filters').append(button)});
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Chiudi':'Menu'};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu'});
document.querySelector('#request').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);const message=`Richiesta di preventivo — Real Tende\n\nNome: ${d.get('name')}\nEmail: ${d.get('email')}\nSoluzione: ${d.get('interest')}\n\n${d.get('message')}`;document.querySelector('#request-text').value=message;document.querySelector('#send-email').href='mailto:realtende8@gmail.com?subject='+encodeURIComponent('Richiesta di preventivo — Real Tende')+'&body='+encodeURIComponent(message);[['#send-one','393491287740'],['#send-two','393519114911']].forEach(([id,number])=>{const a=document.querySelector(id);a.href='https://wa.me/'+number+'?text='+encodeURIComponent(message);a.target='_blank';a.rel='noopener noreferrer'});const result=document.querySelector('#result');result.hidden=false;result.focus()};
const reduce=window.matchMedia('(prefers-reduced-motion: reduce)');if(!reduce.matches&&'IntersectionObserver' in window){document.body.classList.add('effects');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}document.querySelector('#motion').onclick=e=>{const paused=document.body.classList.toggle('paused');e.target.setAttribute('aria-pressed',String(paused));e.target.textContent=paused?'Riprendi effetti':'Pausa effetti'};

