const photoSet=[
 ['piscina.jpeg','Il tuo angolo di benessere','Pergola, piscina e pedana'],
 ['pergola-mare.jpeg','Ombra, con vista','Pergole sul mare'],
 ['pergola-sera.jpeg','La bellezza di restare fuori','Vetrate e atmosfera serale'],
 ['pergola-giardino.jpeg','Una stanza nel verde','Pergola in giardino'],
 ['pergola-studio-chiara.png','Linee essenziali','Presentazione della pergola bioclimatica'],
 ['pergola-dettagli-chiara.png','Dentro il progetto','Illustrazione dei componenti · caratteristiche secondo modello']
];
const gallery=document.createElement('section');gallery.id='galleria';gallery.innerHTML='<div class="section-top"><div><div class="eyebrow">La galleria Real Tende</div><h2>Spazi da vivere.<br><em>Dettagli da guardare.</em></h2></div><p>Tra giardini, terrazze e nuove prospettive. Apri le immagini per scoprire ogni dettaglio.</p></div><div class="photo-grid"></div>';
document.querySelector('.story').before(gallery);
const viewer=document.createElement('dialog');viewer.className='photo-viewer';viewer.setAttribute('aria-label','Galleria fotografica');viewer.innerHTML='<button class="viewer-close" aria-label="Chiudi immagine">Chiudi ×</button><img alt=""><div class="viewer-bar"><button class="viewer-prev" aria-label="Immagine precedente">←</button><p id="viewer-caption"></p><button class="viewer-next" aria-label="Immagine successiva">→</button></div>';document.body.append(viewer);
let currentPhoto=0;function showPhoto(i){currentPhoto=(i+photoSet.length)%photoSet.length;const [src,title,subtitle]=photoSet[currentPhoto];viewer.querySelector('img').src=src;viewer.querySelector('img').alt=title+' — '+subtitle;viewer.querySelector('p').textContent=(currentPhoto+1)+' / '+photoSet.length+' · '+title;if(!viewer.open)viewer.showModal()}
photoSet.forEach(([src,title,subtitle],i)=>{const figure=document.createElement('figure');figure.className='gallery-photo'+(i>=4?' presentation':'');const button=document.createElement('button');button.type='button';button.setAttribute('aria-label','Ingrandisci: '+title);const img=document.createElement('img');img.src=src;img.alt=subtitle;img.loading='lazy';img.decoding='async';button.append(img);const zoom=document.createElement('span');zoom.className='zoom-mark';zoom.textContent='↗';button.append(zoom);button.addEventListener('click',()=>showPhoto(i));const caption=document.createElement('figcaption');const small=document.createElement('span');small.textContent=subtitle;const heading=document.createElement('h3');heading.textContent=title;caption.append(small,heading);figure.append(button,caption);gallery.querySelector('.photo-grid').append(figure)});
viewer.querySelector('.viewer-close').onclick=()=>viewer.close();viewer.querySelector('.viewer-prev').onclick=()=>showPhoto(currentPhoto-1);viewer.querySelector('.viewer-next').onclick=()=>showPhoto(currentPhoto+1);viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});viewer.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();showPhoto(currentPhoto-1)}if(e.key==='ArrowRight'){e.preventDefault();showPhoto(currentPhoto+1)}});
const galleryNav=document.createElement('a');galleryNav.href='#galleria';galleryNav.textContent='Galleria';document.querySelector('nav').insertBefore(galleryNav,document.querySelector('nav .btn'));galleryNav.addEventListener('click',()=>{document.querySelector('nav').classList.remove('open');document.querySelector('.menu').setAttribute('aria-expanded','false');document.querySelector('.menu').textContent='Menu ☰'});
const imageMap={0:[0,0],1:[50,0],3:[100,0],4:[0,100],5:[50,100],6:[100,100]};
document.querySelectorAll('.card').forEach((card,i)=>{const image=document.createElement('div');image.className='category-photo';image.setAttribute('role','img');image.setAttribute('aria-label',card.querySelector('h3').textContent+' — immagine illustrativa');if(imageMap[i]){image.classList.add('generated-category');image.style.backgroundPosition=imageMap[i].map(v=>v+'%').join(' ');const label=document.createElement('span');label.className='inspiration-label';label.textContent='Immagine d’ispirazione';image.append(label)}else{const img=document.createElement('img');img.loading='lazy';img.alt=card.querySelector('h3').textContent;img.src=i===2?'pergola-giardino.jpeg':i===7?'pergola-sera.jpeg':'piscina.jpeg';if(i===8)img.style.objectPosition='center bottom';image.append(img)}card.prepend(image)});
document.querySelector('.hero-art img').src='pergola-mare.jpeg';document.querySelector('.hero-art img').alt='Pergole affacciate sul mare al tramonto';document.querySelector('.art-label').innerHTML='LA GALLERIA REAL TENDE<span>La tua prossima prospettiva.</span>';

